### ISSUE TITLE
README dores not render correctly on PyPi

### ISSUE THREAD

**Issue by dreispt** [liangqing/syncrypto#2]
See https://pypi.python.org/pypi/syncrypto.
My guess is that there could be a few RST syntax error and PyPi falls back to presenting the raw text.

**Comment by liangqing** [comment]
Hi Daniel,

Thanks for your remind, you are right, there are actually some syntax errors in the README.rst.

It is fixed now.

**Comment by dreispt** [comment]
Much better now :smile:
